# Generated by Django 5.0.2 on 2024-02-14 05:07

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_shop_commen_created_d90939_idx_post_commen_created_d2d13f_idx_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
